- src/components/Modal/Modal.jsx
- src/components/Modal/ModalStyles.jsx
- 배경 스크롤 비활성화
- 배경 블러 처리
- 모달 외부 클릭 시 닫기
close #19 
- 애니메이션 일단 제거 (필요성 논의 후 필요하면 다시 삽입하도록 하겠습니다)
- 현재 배경 페이지가 밑으로 내려간 상태에서 popup을 띄워도 배경페이지가 제일 위로 올라간다는 문제점 있음
- 하지만 이는 현재 모달을 페이지 내부에서 사용하는 방식이 아닌 모달 페이지로 넘어가는(페이지간 이동)을 하고 있는 중이라 발생하는 문제로 예상됨 -> 사용하고자 하는 페이지 내부에서 불러오는 형식이라면 문제 없을 것 같음
> [Feat]-Popup Modal 배경 관련 기능 추가

- package.json
- public/index.html
- src/components/CourseDetail/CourseDetailStyle.jsx
- src/components/CourseDetail/CousreDetail.jsx
- src/components/FieldCategory.jsx
- src/components/FieldCategoryInput.jsx
- src/components/Header.jsx
- src/components/Modal/Modal.jsx
- src/components/Modal/ModalContainer.jsx
- src/components/Modal/ModalStyles.jsx
- src/hooks/useClient.jsx
- src/hooks/useOutsideClick.jsx
- src/recoils/atoms.js
- yarn.lock

- Modal 분리
- Modal 상세 정보와 연결
- Modal 직군 선택과 연결
- Close Button -> X 버튼으로 조정
#36 
- 상세페이지 디자인 조정 필요
- 직군 선택 페이지에서 "검색하기" 버튼 눌렀을 시 페이지 이동 필요
- Modal을 분리하니 단순히 `const courseDetail = useRecoilValue(courseDetailState);` 이렇게 데이터를 받아올 수 없었음
```
const [courseDetail, setCourseDetail] = useRecoilState(courseDetailState);
useEffect(() => {
fetch('/data/courseDetail.json')
.then((response) => response.json())
.then((data) => setCourseDetail(data))
.catch((error) => console.error('Error fetching course details:', error));
}, [setCourseDetail]);
```
- 이런식으로 받아오는 방법으로 수정
> [Feat/Fix] Modal 분리 및 상세페이지, 직군 연결

- src/components/CourseDetail/CourseDetailStyle.jsx
- src/components/Modal/Modal.jsx
- src/components/Modal/ModalStyles.jsx
https://github.com/user-attachments/assets/a58b1b9e-0e28-43a2-ab10-50cee0fb1299
- Modal 닫은 후 스크롤 해결
- 로드맵 페이지 모달 닫힘 문제 해결
#44 
- 직군 선택 페이지에서 "검색하기" 버튼 눌렀을 시 페이지 이동 필요
- useEffect 중복으로 인한 문제 -> 해결
> [Fix✏️] 모달 뒤 스크롤 문제 해결 + 타페이지 닫힘 해결

- src/components/CourseDetail/CousreDetail.jsx
- src/components/Header.jsx
- src/hooks/useField.jsx
- 상세 정보 불러오기 (예시 넣어서 불러옴)
- 실제로는 학수번호 넣으면 상세정보 볼 수 있음
#46 
- 로드맵에서 연결 해야함
- recoil 상태 관리 관련 수정
- await 이용 -> 정보 기다릴 때까지 넘어가지 않도록 설정
- 로딩이 느려질 경우 is Loading 창 띄우게 설정
- 정보를 가져오지 못할 경우 -> 예외 처리 창 설정
> [Feat] 상세 정보 API 연결

- src/components/RoadMap/RoadMapContainer.jsx
- src/components/RoadMap/RoadMapTable.jsx
- 다양한 화면 비율에서 공백이나 스크롤이 없도록 구현
> [Feat] 화면 비율에 맞춰 로드맵 비율 수정

- src/components/Modal/FieldCategoryInput.jsx
- src/components/Sidebar/DepartmentListContents.jsx
- src/components/Sidebar/FieldCategory.jsx
- src/hooks/useField.jsx
https://github.com/user-attachments/assets/e0650eb4-0e1a-41ca-8733-59337203724e
- 리뷰를 반영하여 사이드 바 문구를 수정했습니다.
- 직군 선택한 후, 다시 선택창을 열어도 현재 선택된 직군이 입력되어 있습니다.
- fetchSubjectsInField함수에서 선택한 직군 창들을 초기화하는 코드를 삭제했습니다.
> [Edit] - 사이드 바 문구 수정 및 직군 입력창 내용 유지 기능 추

- src/components/GlobalStyle.jsx
- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/CompetencyTable.jsx
- src/components/RoadMap/CourseCreditTable.jsx
- src/components/RoadMap/RoadMapCell.jsx
- src/components/RoadMap/RoadMapCell2.jsx
- src/components/RoadMap/RoadMapTable.jsx
- Cell 테두리 색상을 소프트하게 변경
- 교과목 테이블 스크롤을 가장 밑으로 내렸을 시 Cell 밑부분이 보이지 않는 이슈 수정
- 세부 옵션 선택 박스가 RoadMapColumn 안에만 존재해서 발생하는 사소한 스크롤 문제
- 글씨체가 너무 딱딱한 느낌이 드는 것 같기도 함
> [Fix] Cell border 색상 소프트하게 변경

- src/components/Main.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/components/Sidebar/FieldInput.jsx
- src/components/Sidebar/SearchBar.jsx
- src/components/Sidebar/SearchLog.jsx
- src/hooks/useField.jsx
- 직군으로 검색한 학과 리스트 출력이 간헐적으로 안되는 버그 수정
- 검색바 돋보기 아이콘 추가
- 검색 기록 아이콘 X 표시로 변경
- 모든 검색 기록 지우기 버튼 추가
- 검색 기록 중복 방지
- 로드맵 컨테이너 width 조절
```js
const fetchLogFields = async ({ middleField, smallField, detailField }) => {
try {
// 선택한 학과 초기화
resetSelectedSubjectState();
// 소분류 데이터 가져오기,
const smallFieldResponse = await serverApi.post('/api/v2/field-search/small', middleField);
setSmallFieldState(smallFieldResponse.data);
// 직군창 레이아웃 전환을 위한 소분류 선택 상태를 true로 변경
setIsSmallFieldSelectedState(true);
// 세분류 데이터 가져오기
const detailFieldResponse = await serverApi.post('/api/v2/field-search/detail', smallField);
setDetailFieldState(detailFieldResponse.data);
// 선택 처리를 하기 위해 SelectedFieldState에 값 추가
setSelectedFieldtState({
middleField,
smallField,
detailField
});
// 세분류 코드로 학과 데이터, 강좌 데이터 받아오기를 Promis.All( …
```
> [Edit] 직군 검색 버그 수정 및 기타 디자인 요구사항 반영

- src/components/CourseDetail/CompetitionTable.jsx
- src/components/CourseDetail/CourseDetail.jsx
- src/components/CourseDetail/CourseDetailStyle.jsx
- src/components/CourseDetail/MenuList.jsx
- src/components/Modal/TableComponent.jsx
- src/components/Modal/TableComponent2.jsx
- src/components/RoadMap/RoadMapCell2/DropdownPortal.jsx
- src/components/RoadMap/RoadMapCell2/RoadMapCell2.jsx
- src/components/RoadMap/RoadMapTable.jsx
- src/hooks/useField.jsx
- src/recoils/atoms.js
https://github.com/user-attachments/assets/91f07370-a0d5-4335-8f02-82829de146aa
- 목차 추가
- 과목 설명(부제목) 추가 - (국문설명 위에)
- 영문설명 삭제
- 기본정보 돌리기 (가로 세로 전치)
- 기본 정보 필요 없는 내용  삭제
- 수강 경쟁률 확인하기
-  전체 표 (실 수강인원, 수강 바구니, 수강 정원, 경쟁률)
- 1,2,3,4학년 버튼으로 인해 변경할 수 있도록 로직 구성
- 출처 문구 추가 - (* 2023,2024학년도 데이터를 기준으로 산출하였습니다)
- null 값이나 0 - 작대기 채우기
- 목차에서 부제목을 누르면 해당 설명으로 넘어가는 기능 개발
#102 
- Api 500 오류가 뜨는 경우가 꽤나 빈번하게 있었습니다 (되는 경우도 많아서 정확히 어떤 원인인지 모르겠습니다)
- 해당 과목 경쟁률 정보가 없어서 그런 것인지? 통신이 안 되고 있는지?
- 이 부분은 확인이 필요할 것 같습니다
> [Feat] 상세정보 모달 수정 + 수강 경쟁률 추가

- src/components/RoadMap/CourseCreditTable.jsx
- src/components/RoadMap/RoadMapContainer.jsx
https://github.com/user-attachments/assets/abeb9384-bcfc-496e-a770-71f1a2c093df
- 한 학기에 같은 학수 아이디를 가진 과목 중복방지
- 내 로드맵에 추가한 과목에 대해 '실제 학과' 데이터 추가
- 총 담은 학점 수 출력 및 넘침 방지 기능 추가
```js
if (!haksuIdToCompetencyMap.has(haksuId)) {
haksuIdToCompetencyMap.set(haksuId, [{ competencyName, competencyCode }]);
} else {
const competencies = haksuIdToCompetencyMap.get(haksuId);
// 중복 역량 방지 후 추가
if (!competencies.some((comp) => comp.competencyCode === competencyCode)) {
competencies.push({ competencyName, competencyCode });
}
return; // 중복 학수 ID일 경우 이후 로직 스킵
}
```
- map에 key값으로 학수아이디를 가진다. 이때 현재 학수아이디가 이미 key값으로 존재한다면 해당 학수아이디의 전공역량에 대해서 넣을지 말지 판단한 뒤, 이후 테이블에 추가하지 않는다.
---
```js
const cellData = {
haksuId: haksuId,
courseName: name,
courseCredit: credit,
subjectName: openingSubject, // 현재 과목이 실제로 열리는 학과 …
```
> [Edit] 로드맵 컨테이너 관련 버그 수정 및 총 담은 학점 수 보여주기 기능 추가

- src/components/RoadMap/RoadMapCell2/RoadMapCell2.jsx
- 교과목 Cell에 포함된 competencies의 내용이 "전공역량코드 배열"에서 "{전공역량코드, 전공역량이름} 배열"로 수정됨에 따라 발생한 하이라이트 오동작 이슈를 해결했습니다.
> [Fix] 전공역량 하이라이트 기능 픽스

- src/components/CourseDetail/CompetitionTable.jsx
- src/components/CourseDetail/CourseDetail.jsx
- src/components/CourseDetail/MenuList.jsx
- src/components/Modal/TableComponent.jsx
- src/components/Modal/TableComponent2.jsx
https://github.com/user-attachments/assets/e6d55819-80b1-420c-8343-2350e3079b10
- 표 크기 기존 "전공역량 표"와 통일
- 표의 디자인 기존 "수강신청 경쟁률"과 통일
- 목차의 디자인 수정
`word-wrap: break-word;`
- 창의 크기가 작아져서 표의 크기가 작아질 경우 자동 줄바꿈 설정
close #111 
> 목차의 표도 같은 디자인으로 통일할 것
- 2가지 버전으로 만들어 놓은 상태
- 1안 : 기존 회색에서 색상만 초록색 개열 바꾼 버전
- 2안 : 아래 3가지 표와 완전히 동일한 상태로 바꾼 버전
- 기획의 확인을 받고 둘 중 선택해서 적용
- 현재는 1안으로 되어있음
> [Fix] 상세 모달 내부 디자인 3차 수정

- src/components/Sidebar/FieldInput.jsx
- src/components/Sidebar/SearchBar.jsx
- 직군에 대한 검색기록 코드를 수정하였습니다.
```js
if (newLog.length > 5) {
newLog.pop();
}
```
- 검색기록이 5개가 넘을 시 pop 메소드를 사용하여 가장 오래된 기록을 삭제합니다.
> [FIx] 직군 검색기록 코드 수정

- src/components/CourseDetail/CompetitionTable.jsx
- src/hooks/useField.jsx
- 404 에러 뜰 경우 해당 학기에 과목이 미개설 되었다고 알려주는 문구 추가
- 2024학년도 데이터만을 이용했기에 이에 맞춰서 문구 수정
```
const fetchCompetitionRate = async (haksuId) => {
try {
const res = await serverApi.get(`/api/v1/competition-rate/${haksuId}`);
return res.data;
} catch (error) {
console.error('Error fetching competition rate:', error);
throw error;
}
};
```
- 404 에러가 뜰 떄 처리를 따로 해줘야하기 떄문에 동기 함수로 바꾸었습니다
- ErrorMessage의 유무에 따라 테이블을 띄울지 문구를 띄울지 결정
close #115 
- 이후 APi 수정되면 학기 구분하여 띄우는 작업 진행하겠습니다
> [Fix] 경쟁률 관련 404 에러 처리

- src/App.jsx
- src/components/GlobalStyle.jsx
- src/font/font.css
수정 전
https://github.com/user-attachments/assets/edbb4030-5645-47b3-a764-063cdda68555
수정 후
https://github.com/user-attachments/assets/d9d83886-674b-4340-9c38-b685825459b4
- 이슈 현상: 맥 환경에서는 덜하지만, 윈도우 환경에서 서비스를 실행할 때, 심한 폰트 떨림 현상이 존재함.
- 이슈 발생 이유: styled-components는 스타일이 render 될 때 마다 head 태그 내의 style 태그를 변경하는데, 이로 인해 새로운 스타일이 render 되면 폰트를 재요청 하기 때문에 깜빡임 현상이 발생.
- 해결 방안: GlobalStyle.jsx에서 설정한 font-family를 css 파일로 옮겨서 styled-components 밖에서 리소스를 요청하는 방식으로 해결.
> [Fix] 폰트 버벅임 이슈 해결

- src/components/RoadMap/CompetencyTable.jsx
- src/components/RoadMap/RoadMapCell2/RoadMapCell2.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/components/RoadMap/RoadMapTable.jsx
- 학과 이동 간 발생한 로드맵의 fadeIn 에러 수정
- 전공역량 테이블 간격 수정
- 스크롤 성능 개선
- 전체 학과 -> 특정 학과로 넘어갈 때 로드맵 테이블의 fadeIn 애니메이션이 적용되지 않던 에러 수정
- 로드맵 테이블의 fadeIn 애니메이션이 눈에 띄도록 10ms delay 추가
- 전공역량 테이블에서 전공역량 Cell 항목이 많아지면 전공역량 제목 컨테이너가 살짝 줄어드는 에러 수정
- 기존에 스크롤 변동 시 마다 감지 함수를 호출하여 스크롤 버벅임이 심했던 현상을 100ms 간격을 주어 성능 개선
> [Fix] design/roadmap-table의 에러 수정

- src/components/CourseDetail/CompetitionTable.jsx
- src/components/Modal/TableComponent.jsx
- 교과목 상세정보 모달 오픈 시 발생하던 2가지 에러 해결
- "Warning: React does not recognize the `isHeader` prop on a DOM element." 에러 메세지 해결
- "Warning: Received `true` for a non-boolean attribute `active`." 에러 메세지 해결
- isHeader 삭제: 사용하지 않는 변수인 것 같아 삭제했습니다.
- active 가 boolean 값을 가질 경우, HTML의 Attributes는 boolean 타입을 가질 수 없기 때문에, 해당 변수가 StyledComponents의 props로 전달될 의도라고 하더라도 에러를 발생하는 것으로 이해했습니다. 따라서 active 변수 앞에 $를 붙여 DOM 요소로 렌더링 되지 않도록 처리하여 이슈를 해결했습니다.
- 참고: https://velog.io/@yeonbot/Warning-Received-true-for-a-non-boolean-attribute-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0
- 혹시 지우면 안됐거나 제가 발견하지 못한 기능의 이상이 발견되면 알려주세요!
> [Fix] 모달 오픈 시 에러 메세지 발생 이슈 해결

- src/components/FieldSearchBar/DepartmentList.jsx
- src/components/FieldSearchBar/DepartmentListContents.jsx
- src/components/FieldSearchBar/FieldInput.jsx
- src/components/FieldSearchBar/FieldSearchBar.jsx
- src/components/FieldSearchBar/SearchBar.jsx
- src/components/FieldSearchBar/SearchLog.jsx
https://github.com/user-attachments/assets/74efdbd1-70ce-45e8-9c0c-e40e2f344698
- 선생님들 의견을 반영하였습니다.
1. 맨 처음 중분류 그리드를 '사람인'과 동일한 스타일
2. 각 직군 아이템 테두리 제거 및 글자에 색상 추가
3. 각 직군별 구분하는 그림자 -> 옅은 구분선 처리
4. 검색기록 테두리 삭제
5. 직군 검색 전체 컨테이너 그림자 삭제
> [Design] 직군 선택 그리드 및 리스트 형태 스타일 수정

- src/components/FieldSearchBar/SearchBar.jsx
- src/components/Main.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- 직군 검색창과 로드맵 컨테이너 간격을 줄였습니다.
- 로드맵 컨테이너 제목 폰트사이즈를 줄였습니다.
- 검색 창 안에 있는 폰트 크기를 14px로 맞췄습니다.
> [Design] 사소한 스타일 수정

- src/components/CourseDetail/CompetitionTable.jsx
- src/components/CourseDetail/CourseDetail.jsx
- 경쟁률 API 학기 구분하여 받아오기
- 1,2학기 설정할 수 있는 버튼 추가 
- 학기별로 해당 학기 경쟁률 띄워주기
- 제목 옆으로 1,2학기 설정 버튼 위치 이동
close #148 
- 1,2학기를 먼저 선택하고 -> 1,2,3,4학년을 선택하는 것이 원하는 이용경로
- 이대로 사용자가 따라올 수 있을지 의문 (1,2학기 선택과 학년 선택을 구별할 수 있는 수단이 있으면 좋을 것 같음 _-> 피드백으로 해결 완!_
> [Feat] 경쟁률 API 학기 구분

- src/components/FieldSearchBar/FieldSearchBar.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/recoils/atoms.js
https://github.com/user-attachments/assets/b8cb8624-b250-4749-8ece-71f0889bccff
- URL 공유시 위에 선택한 직군 정보도 같이 불러와집니다.
```js
// URL을 통한 접속
useEffect(() => {
const myTableData = searchParams.get('myTableData');
const selectedFieldData = searchParams.get('selectedFieldData');
if (myTableData && selectedFieldData) {
navigate('/road-map');
const decodedMyTableData = decodeData(myTableData);
setSelectedMyTableContentsState(decodedMyTableData);
const decodedSelectedFieldData = decodeData(selectedFieldData);
fetchLogFields(decodedSelectedFieldData);
setIsShowDepartAndLog(true);
}
}, []);
```
- URL 정보에 선택한 직군 정보도 추가하였습니다.
- 기존에 검색기록을 불러올때 사용중인 fetchLogFields 함수를 그대로 사용하였습니다.
- 학과 및 검색기록 보여주는 상태를 전역으로 변경하였는데, 이를 좀 더 깔끔하게 사용할 수 있는 방법이 있을 것 같습니다.
> [Feat] URL 공유시 선택한 직군 정보도 같이 공유되는 기능 추가

- src/components/FieldSearchBar/FieldInput.jsx
- URL을 통해 불러온 직군이 자동 스크롤이 이루어지지 않는 버그를 수정했습니다.
```js
useEffect(() => {
if (selectedField) {
fieldRefs.middle.current[selectedField.middleField?.middleField]?.scrollIntoView(scrollOption);
fieldRefs.small.current[selectedField.smallField?.smallField]?.scrollIntoView(scrollOption);
fieldRefs.detail.current[selectedField.detailField?.detailField]?.scrollIntoView(scrollOption);
}
}, [selectedField]);
```
- selectedField를 통해 ref 추가하는 구문을 useEffect로 관리하도록 했습니다.
> [Fix] URL 공유시 직군 스크롤 추적 안되는 버그 수정

- src/components/AboutKumapContents/AboutCompetencyContents.jsx
- src/components/AboutKumapContents/AboutKumapContents.jsx
- src/components/AboutUsContents/AboutUsContens.jsx
- src/components/AboutUsContents/BackgroundContents.jsx
- src/components/AboutUsContents/IntroductionProfileContents.jsx
- src/components/AboutUsContents/IntroductionTitleContent.jsx
- src/components/AboutUsContents/LogoContents.jsx
- src/components/Footer/Footer.jsx
- src/components/HeaderBar.jsx
- src/components/HomeContents/BackgroundContents.jsx
- src/components/HowToPageContents/HowTo.jsx
- src/pages/AboutKumap.jsx
- src/pages/AboutUs.jsx
- 배경 원에 커서를 올리면 스크롤이 되지 않던 이슈를 해결하였습니다.
- 건국대학교 로고를 클릭해도 컨국대학교 홈페이지로 이동하지 않는 이슈를 해결하였습니다.
- 컴포넌트의 z-index를 전체적으로 수정하여 배경은 -1, 중요한 컴포넌트만 1 또는 2의 값을 가지도록 수정하여 배경 컴포넌트가 다른 컴포넌트 위에 레이어 되지 않도록 수정하였습니다.
- HeaderBrand가 a 태그로 렌더링되지 않을 경우, 클릭해도 링크가 작동하지 않을 수 있습니다. 따라서 div 였던 태그를 a 로 수정하였습니다.
- 모니터의 크기가 달려져도 최대한 일정한 화면을 출력하도록 수정하고 있습니다.
- 이미지를 효율적으로 출력하는 방법에 대해 고민하고 있습니다.
- 로드맵 로직을 분리 시키는 작업은 추후에 진행하도록 하겠습니다.
> [Fix] z-index를 수정하여 레이어 이슈 해결

- src/components/FieldSearchBar/FieldGridContents.jsx
- src/components/FieldSearchBar/FieldInput.jsx
- src/components/FieldSearchBar/FieldListContents.jsx
- src/components/FieldSearchBar/SearchBar/SearchBar.jsx
- src/components/FieldSearchBar/SearchLogContent/SearchLogContent.jsx
- src/components/FieldSearchBar/index.js
- src/hooks/useField.jsx
- src/recoils/atoms.js
- src/recoils/useAtomReducer.jsx
```js
const handleMiddleFieldClick = async (field) => {
await fetchSmallField(field);
setSelectedField({ middleField: field });
setSubjectsInField([]);
};
```
```js
// dispatch 구현
const dispatch = useRecoilCallback(
({ set }) =>
(action) => {
switch (action.type) {
case 'clickMiddle':
set(selectedFieldState, { middleField: action.field });
set(subjectsInFieldState, []);
break;
default:
break;
}
},
[]
);
// 실제 사용처
const handleMiddleFieldClick = (field) => {
fetchSmallField(field);
dispatch({ type: 'clickMiddle', field });
};
```
- dispatcher 구현을 통해 코드의 모듈화 및 일관성을 유지하고자 했습니다.
- 비동기 작업과 상태 업데이트를 깔끔하게 분리했습니다.
```js
export const selectedFieldLogSelector = selector({
key: 'selectedFieldLogSelector',
get: ({ get }) => get(selectedFieldLogState),
set: ({ get, set }, updatedFieldCodeList) => { …
```
> [Refactor] 검색 기능 리팩토링
