- .eslintrc
- src/components/NavBar.jsx
- src/pages/RoadMap.jsx
- Figma 초기 디자인을 바탕으로 NavBar 컴포넌트를 구현했습니다.
- styled-component를 이용하여 디자인 적용했습니다.
> [Feat] - NavBar 초기 구현

- package.json
- src/Animation/Animation.css
- src/components/Backdrop/Backdrop.css
- src/components/Backdrop/Backdrop.js
- src/components/List/List.css
- src/components/List/List.jsx
- src/components/Modal/Modal.css
- src/components/Modal/Modal.jsx
- src/components/Sidebar/Sidebar.css
- src/components/Sidebar/Sidebar.jsx
- src/pages/Home.jsx
- src/pages/Main/Main.css
- src/pages/Main/Main.jsx
- src/pages/RoadMap.jsx
- yarn.lock
- 사이드 바 추가
- 로드맵 더미 데이터 이용해서 추가
- 애니메이션 추가
> [Feat] - 로드맵 페이지 예시 제작

- src/Animation/Animation.jsx
- src/components/List.jsx
- src/components/Modal.jsx
- 학과 로드맵에서 내 로드맵으로 과목 add하고 delete되는 기능
- 내 로드맵에서 학과 로드맵으로 과목 add하고 delete되는 기능
> item add, delete 기능 추가

- src/App.jsx
- src/components/Header.jsx
- src/pages/Home.jsx
- useNavigate를 이용한 라우팅으로 변경했습니다.
- 사용하지 않는 주석들은 삭제했습니다.
> [Refactor] - useNavigate 사용 및 주석 삭제

- src/components/DepartmentList.jsx
- src/components/FieldCategory.jsx
- src/components/Sidebar.jsx
- src/components/SidebarContents.jsx
- 진출분야를 보여주었습니다.
- 진출분야에 해당하는 과들을 보여주고 선택할 수 있도록 했습니다.
> [Feat] - 사이드 바 내용 초기 구현

- src/components/Header.jsx
> [Fix]-Merge Collision 해결

- src/components/Header.jsx
- src/pages/RoadMap.jsx
- 로드맵 페이지에 기존 Navbar 대신 Header 컴포넌트로 변경
- useLocation을 이용하여 현재 경로를 가져옴
> [Edit] - Navbar 내용을 Header 내용으로 변경

- src/components/List.jsx
- src/components/Main.jsx
> 코스 변경 시 로드맵 변경되는 기능 추가

- src/components/RoadMap/RoadMapTable.jsx
- 로드맵 container 간소화
close #24 
- mockData와 연결 필요
> 로드맵 container 간소화

- public/data/courseDetail.json
- src/components/Modal/Modal.jsx
- src/components/Modal/ModalStyles.jsx
- src/components/TableComponent2.jsx
- src/hooks/useClient.jsx
- src/recoils/atoms.js

- api 받아오는 형식 바꾸고 -> 해당 형식에 맞게끔 받아옴( 추후 변동 가능성 있음)
-   상세페이지 mockData 생성 
-  정보 연결
#33
- 모달 분리 전
> [Feat 💡] 상세페이지 mockData 생성 + 정보 연결

- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/CompetencyTable.jsx
- src/components/RoadMap/RoadMapCell.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/components/RoadMap/RoadMapTable.jsx
-  내 로드맵에 과목 추가 시 해당 과목의 전공역량이 전공역량 표에 출력되는 기능 추가
- 테이블 렌더링 시점 다시 생각해보기
- 코드 구성 다시 생각해보기
> 내 로드맵에 과목 담는 기능 추가 및 보완

- src/components/DepartmentList.jsx
- src/components/FieldCategoryInput.jsx
- src/hooks/useApi.jsx
- src/hooks/useClient.jsx
- src/hooks/useField.jsx
- src/recoils/atoms.js
https://github.com/user-attachments/assets/d29bc3ce-73ce-4832-8ae3-35d5d3be4076
- api로부터 실제 데이터를 받아왔다.
- 기존 useClient 훅에서 field 관련 부분만 별도의 useField 훅으로 분리했다.
#42
> [Feat] - 진출분야 및 관련 학과 입력 창 구현

- public/index.css
- public/index.html
- src/components/DepartmentList.jsx
- src/components/FieldCategory.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/components/RoadMap/RoadMapTable.jsx
- src/components/Sidebar.jsx
- src/components/SidebarContents.jsx
- 사이드 바 디자인을 적용했습니다.
- 사이드 바 숨김 버튼을 없앴습니다.
- 로드맵 CSS 를 조정하였습니다.
> [Feat] - 사이드 바 디자인 적용

- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/CompetencyTable.jsx
- src/components/RoadMap/RoadMapCell.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/components/RoadMap/RoadMapTable.jsx
- src/hooks/useField.jsx
- api 추가
- 전공역량 하이라이트 기능 추가
- 1학년 추가
- 1학기, 2학기 과목 처리
> [Feat] API 추가, 전공역량 하이라이트 기능 추가

- .github/workflows/npm-publish.yml
develop 브랜치에 merge 될 시 자동으로 서버에 배포가 진행될 수 있도록 CD 스크립트를 작성하였습니다.
> 프론트 CD 스크립트 작성

- package.json
- src/components/DepartmentList.jsx
- src/components/Header.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/hooks/useField.jsx
- src/pages/Home.jsx
- src/recoils/atoms.js
- yarn.lock
https://github.com/user-attachments/assets/4a2e1b9a-7885-4ca1-89fd-aea59de4c12a
- 선택한 학과에 대하여 전체 로드맵 클릭시 정보를 fetch 합니다.
- 불필요한 스타일 정리를 진행했습니다.
> [Feat] - 전체 로드맵 api 연동 및 기타 스타일 조정

- src/components/CompetencyDetail/CompetencyDetail.jsx
- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/CompetencyTable.jsx
- src/components/RoadMap/RoadMapCell.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/components/RoadMap/RoadMapTable.jsx
- src/recoils/atoms.js
- yarn.lock
> eslint prettier 충돌 문제 해결

- package.json
- src/components/RoadMap/RoadMapContainer.jsx
- src/pages/RoadMap.jsx
- yarn.lock
<p>
<br/>
</p>
- 아이콘 floating 버튼 생성 (스크롤 해도 유지)
- 내 로드맵 사진으로 저장 기능 추가
- html2canvas 이용
```
const handleCaptureButtonClick = () => {
if (roadmapContentRef.current) {
html2canvas(roadmapContentRef.current)
.then((canvas) => {
const link = document.createElement('a');
link.href = canvas.toDataURL('image/png');
link.download = 'roadmap.png';
link.click();
})
.catch((error) => {
console.error('Error capturing the element:', error);
});
} else {
console.error('Roadmap content is not available');
}
};
```
```
<Content ref={roadmapContentRef} id="roadmap-content">
```
- 캡처영역 설정해서 캡처 (내 로드맵) 
#78
- url 여부 회의 때 논의
> [Feat] 내 로드맵 공유 기능(사진)

- src/components/AboutUsContents/AboutUsContens.jsx
- src/components/AboutUsContents/IntroductionProfileContents.jsx
- src/components/AboutUsContents/ProfileContents.jsx
- src/components/Header.jsx
- src/components/HeroContents/GreetTextContents.jsx
- src/pages/AboutUs.jsx
- src/pages/HowTo.jsx
> [Edit] - 최종 발표 전 수정사항 수정 1

- src/components/AboutKumapContents/AboutCompetencyContents.jsx
- src/components/AboutKumapContents/AboutKumapContens.jsx
- src/components/AboutKumapContents/ConclusionContents.jsx
- src/components/Header.jsx
- src/pages/AboutKumap.jsx
> [Feat] KUMAP 소개 페이지 수정 및 헤더 문구 수정

- package.json
- src/components/AboutKumapContents/AboutCompetencyContents.jsx
- src/components/AboutKumapContents/ConclusionContents.jsx
- src/components/AboutUsContents/AboutUsContens.jsx
- src/components/AboutUsContents/IntroductionContents.jsx
- src/components/AboutUsContents/IntroductionProfileContents.jsx
- src/components/AboutUsContents/IntroductionTitleContent.jsx
- src/components/AboutUsContents/ProfileContents.jsx
- src/components/Footer/Footer.jsx
- src/components/HeaderBar.jsx
- src/components/MainContainer.jsx
- src/components/RoadMap/CompetencyTable.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/hooks/useField.jsx
- src/pages/AboutKumap.jsx
- src/pages/AboutUs.jsx
- src/pages/HowToPage.jsx
- src/pages/RoadMap.jsx
- yarn.lock
https://github.com/user-attachments/assets/56ced266-3d0c-493c-8899-b311d4ffafad
- react-fullpage 라이브러리를 이용해 full page 애니메이션을 적용했습니다.
- 쿠맵이란? 페이지와 About Us 페이지에 적용했습니다.
- Header 컴포넌트에 대한 이름을 HeaderBar로 변경했습니다.
- 더 효과적이게 full page 애니메이션 적용할 순 없을까?
- footer의 크기가 페이지 마다 다른데 이를 고정할 순 없을까?
> [Feat] - full page 애니메이션을 적용

- src/components/AboutUsContents/ProfileContents.jsx
- src/components/Footer/Footer.jsx
<p align="center">
</p>
- 글씨가 모두 볼드체로 처리되어서 시선이 분산됨 -> 설명 부분은 regular로 수정
- 과  및 role 글씨체 조금 줄임
<p align="center">
</p>
- 글씨가 모두 볼드체로 처리되어서 시선이 분산됨 -> Footer부분 regular로 수정
- 구현하신 내용을 적어주세요
- 없음
close #93 
- 없음
> [Fix] 폰트 굵기, 크기 및 간격 조정

- src/components/AboutKumapContents/AboutCompetencyContents.jsx
- src/components/AboutKumapContents/AboutKumapContens.jsx
- src/components/AboutKumapContents/ConclusionContents.jsx
- src/components/AboutUsContents/IntroductionContents.jsx
- src/components/AboutUsContents/IntroductionTitleContent.jsx
- src/components/CompetencyDetail/CompetencyDetail.jsx
- src/components/CompetencyDetail/CompetencyDetailStyle.jsx
- src/components/GlobalStyle.jsx
- src/components/HeaderBar.jsx
- src/components/HeroContents/LinkContents.jsx
- src/pages/AboutKumap.jsx
- src/pages/HowTo.jsx
- src/pages/HowToPage.jsx
- 사용법 페이지에 full-page 적용
- 문구 수정
- 버튼 폰트 수정
> [Feat] 사용법 페이지에 full-page 적용 및 헤더 수정

- src/pages/HowTo.jsx
> [Fix] 사용법 페이지 마진 수정

- src/components/HeaderBar.jsx
- src/pages/HowTo.jsx
> [Fix] 사용법 페이지 마진 수정 및 헤더 문구 수정

- package.json
- src/App.jsx
- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/CourseCreditTable.jsx
- src/components/RoadMap/RoadMapCell.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/components/RoadMap/RoadMapTable.jsx
- src/components/RoadMap/SaveButton.jsx
- yarn.lock
- 스크린샷 버튼을 다운로드 버튼으로 수정 후, 호버 시 URL과 스크린샷 중 선택 가능하도록 구현
- 내 로드맵 정보가 포함된 URL로 접속 시, 내 로드맵이 출력되도록 구현
- 내 로드맵 밑에 학과 별 학점이 출력되도록 구현
- URL을 사용자에게 보여줄 방법을 생각해야함 (현재는 console.log 로 출력된 내용을 .../roadmap/~ 뒤이어 쓰면 동작)
- 예시 링크: http://localhost:3000/road-map/eJzdlk1LAkEYx7%2FKMmejnVldxZt6iII6dRMPvixkb4arh4hAawPZkgxWfEFjDS0ChaUoPNQXcp79Ds2mWe1a2qGD3pZn%2Fs%2Fs%2FJ7%2F8wwTDh%2BhreiOnF1NID%2FikQvFU9m0LG1E9yQWwNwSh9FxxDVdRqbLyHA311dRcC0YwLzHS%2Bxis6rQixztvtDbrlmujZdDaSmRzCC%2F4EJyNrYtxTOjhLF08Pjyrt47kDLSfvwwlEpIMvKzs33GvuUMnkrQaC2zPJYNeo4qJRYFtW2qfcdOFi4RvT6BFyxilJTXDzejsV22kElnJRtdYCXAu0VBtNNBoz0rFzzof4TSNLjLmUqfY7%2BgRQ3OeyybA%2BMVWgboeW7QN8x6kaodqncm82HiEX%2Fgm8VkMtlk7DAZClXrjB%2FOkf9xGW7OzPI9I1%2BGZw1O89YXfVZAaVrVgJPu4FH%2FxWc8g88MUPQIRLADsp1BV6DSs%2BiocQkVA9SnOccUvA4fdYU1FVyXrNYq1%2FD8k44G1%2BcgbV5B% …
> [Feat] URL 추출 기능, URL 접속 기능, 학과 별 학점 출력 기능 추가

- package.json
- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/RoadMapCell2.jsx
- src/components/RoadMap/RoadMapTable.jsx
- src/components/TotalRoadMapContents/totalRoadMapCell.jsx
- yarn.lock
#99 
</br></br>
- 왼오 구분되지 않게 수정 → 과목명 옆에 …모양 버튼 추가
- …버튼 누르면→ 상세정보, 내 로드맵에 추가 → 드롭박스 나오게 끔
- 다른 과목 버튼 눌렀을 시 이전 드랍박스는 자동으로 닫히도록 처리
- ...버튼 삭제 -> 버튼 누르면 같은 동작 실행하도록 수정
</br></br>
-최대한 있는 코드를 재사용하도록 했습니다
- 원래 ButtonWraper(Left,Right)이 나누어져있었는데 -> 더 이상 나눌 필요가 없어서
- 컴포넌트명을 Button으로 통일 (CompentencyCell, RoadmapCell2 부분)
- RoadMapCell은 학기를 보여주는 곳에서만 사용 중 (이 부분은 수정 X)
- 세계의 버튼 들이 있어서 향후 통일 필요
</br></br>
- 컴포넌트 종류 통일
- 안에 함수 수정 (로드맵 추가, 상세정보 보기)
</br></br>
(해당 사항 노션에도 작성해놓았습니다)
</br>
- 일정 글자 수 이상이면 …으로 표시되어있는 기능이 들어가있지 않음
- 메인 로드맵 페이지와 달리 클릭하여 상세정보를 보는 것이 불가하기에 …으로 처리한다면 평생 그 과목의 풀네임을 알 수 없는 상황이 발생하기 때문으로 추정
- 대신 칸의 크기가 비례하여 커짐
- **이대로 유지? vs 가시화를 위해 …기능 도입**
> [Feat] 드롭박스 구현 및 버튼 UX 최적화

- package.json
- src/components/FloatButton/SaveButton.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- yarn.lock
- 버튼 툴팁 추가
- 버튼 클릭 시 성공 알림(토스트) 추가
- Copy URL 클릭 시 클립보드에 주소가 복사 되도록 기능 추가
- 유효성은 보지 않고 버튼 클릭 시 무조건 성공 알림(토스트)가 발생함
> [Feat] 버튼 기능 추가

- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/RoadMapCell2/RoadMapCell2.jsx
https://github.com/user-attachments/assets/73c1937d-27fd-4875-ae0b-b0d33556c944
- 교과목 Cell과 전공 역량 Cell 등장 시 fade in 효과를 주는 애니메이션 추가
> [Feature] 로드맵 내에서 Cell 등장 시 fade 효과 추가

- src/components/FieldSearchBar/FieldInput.jsx
- src/components/FieldSearchBar/SearchBar.jsx
- src/components/FieldSearchBar/SearchLog.jsx
https://github.com/user-attachments/assets/c3da8547-71a8-440e-91a2-fd103b757cab
- 검색기록의 수정된 디자인을 반영하였습니다
> [Design] 검색기록 관련 UI 수정

- src/components/FieldSearchBar/DepartmentList.jsx
- src/components/FieldSearchBar/DepartmentListContents.jsx
- src/components/FieldSearchBar/FieldInput.jsx
- src/components/FieldSearchBar/FieldSearchBar.jsx
- src/components/FieldSearchBar/SearchBar.jsx
- src/components/FieldSearchBar/SearchLog.jsx
- src/components/HeaderBar.jsx
- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/RoadMapCell2/RoadMapCell2.jsx
- src/hooks/useField.jsx
- src/style/Frames.jsx
https://github.com/user-attachments/assets/189a4479-800f-4bb8-ba33-63dbd7d9fee2
- 직군 검색창 전체에 대한 토글을 추가하였습니다.
- 맨 처음에는 학과 리스트 및 검색 기록이 안보이도록 했습니다.
- 학과 리스트에 보여줄 것이 없다면 안보이도록 했습니다.
- 중,소,세분류를 구분하는 선을 border-shadow로 처리하였습니다.
- 그리드 비율을 조절하여 직군과 학과 Cell의 width를 맞췄습니다.
- 기존에 뜨던 styled-component props 관련한 오류를 모두 해결했습니다.
- [Summer.dev [styled-components] props error 해결](https://summerr.tistory.com/106)을 참고하여 prop이름에 '$' prefix를 추가하여 styled-component props 에러를 해결하였습니다.
```js
background-color: ${({ $isSelected }) => ($isSelected ? '#d3d3d3' : 'white')};
```
- 디자인에 대해서 좀 더 고민해봐야 할 것 같습니다.
- 너무 하얀색인 느낌이 강한 것 같습니다.
> [Feat] 직군검색창 토글 구현 및 CSS 변경

- package.json
- yarn.lock
> [Chore] serve 라이브러리 추가

- .github/workflows/npm-publish.yml
- serve하는 구문 및 npm,npx 버젼 체크 구문 추가
> [Chore] serve하는 구문 및 npm,npx 버젼 체크 구문 추가

- .github/workflows/npm-publish.yml
> [Chore] yarn serve를 통한 빌드 실행

- .github/workflows/npm-publish.yml
> [Chore] 빌드시 상세한 로드 출력

- .github/workflows/npm-publish.yml
- 기존 사용중인 3000번 포트 kill 하는 구문 추가
> [Chore] 기존 사용중인 3000번 포트 kill 하는 구문 추가

- .github/workflows/npm-publish.yml
> [Typo] yaml 들여쓰기 수정

- .github/workflows/npm-publish.yml
> [Fix] sudo없이 프로세스 종료

- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/CompetencyTable.jsx
- src/components/RoadMap/CourseCreditTable.jsx
- src/components/RoadMap/RoadMapCell.jsx
- src/components/RoadMap/RoadMapCell2/RoadMapCell2.jsx
https://github.com/user-attachments/assets/605fa084-4769-4257-b889-00892925a240
- 로드맵 테이블 및 셀 보더 제거 + 색 추가
- 하이라이트 색 변경
- 담은 학점 컨테이너 디자인 수정
- 좀 칙칙한 것 같아서.. 컨테이너 및 셀 색상 자유롭게 의견 제시해주시면 수정해서 보여드리겠습니다!
> [Design] 로드맵 테이블 및 셀 디자인 수정

- src/components/FieldSearchBar/SearchBar.jsx
- fetch api가 수정됨에 따라 body data의 구조를 변경하였습니다.
```js
const restructuredFieldData = {
middleField: {
middleField: field.middleField,
middleFieldCode: field.middleFieldCode
},
smallField: { smallField: field.smallField, smallFieldCode: field.smallFieldCode },
detailField: { detailField: field.detailField, detailFieldCode: field.detailFieldCode }
};
```
- 각 분류마다 code를 필요로 해졌으므로 코드 어트리뷰트를 추가하였습니다.
> [Fix] api수정에 따른 fetch data 수정

- src/components/RoadMap/CompetencyCell.jsx
- src/components/RoadMap/CompetencyTable.jsx
- src/components/RoadMap/CourseCreditTable.jsx
- src/components/RoadMap/RoadMapCell.jsx
- src/components/RoadMap/RoadMapCell2/RoadMapCell2.jsx
- src/components/RoadMap/RoadMapContainer.jsx
- src/components/RoadMap/RoadMapContents.jsx
- src/components/RoadMap/RoadMapTable.jsx
- src/components/TotalRoadMapContents/totalRoadMapCell.jsx
https://github.com/user-attachments/assets/db6ebc1c-4d65-49cf-b8f5-c4cec81fb08a
- Cell 호버 기능: Cell 배경색 변경 -> 글씨 색상 변경으로 수정
- 담은 과목(unclickable) + 하이라이트 되었을 경우에 대해 새로운 색상으로 Cell의 배경색 변경
- 전체 학과 로드맵 버튼 텍스트 볼드 처리
- 전공역량 테이블 내 타이틀 검색창 타이틀과 동일한 폰트 사이즈로 수정
- 드롭박스가 보이지 않을 경우 아래로 스크롤 되도록 처리
- 담은 과목(unclickable) + 하이라이트 되었을 경우에 대한 새로운 배경 색상 고민
> [Design] 로드맵 / 전공역량 테이블 디자인 수정

- Dockerfile
> [Chore] 도커파일 추가

- src/pages/NewHome.jsx
- src/style/Frames.js
- 홈 페이지에 들어가는 문구를 수정했습니다.
- 진로를 탐색하고 추가하여 -> 진로를 탐색하고 수업을 추가하여
> [Fix] 홈 페이지 문구 수정

- package.json
- yarn.lock
> [Chore] downgrade eslint version

- package.json
- yarn.lock
> [Chore] remove useless library

- src/components/RoadMap/RoadMapContainer.jsx
- src/hooks/useApi.jsx
> [Fix] Change  new baseUrl

- src/components/RoadMap/RoadMapContainer.jsx
- src/hooks/useApi.jsx
> [Fix] base url

- public/index.html
- src/components/AboutUsContents/AboutUsContens.jsx
- src/components/AboutUsContents/BackgroundContents.jsx
- src/components/AboutUsContents/IntroductionContents.jsx
- src/components/AboutUsContents/LogoContents.jsx
- src/pages/AboutKumap.jsx
- src/pages/AboutUs.jsx
> [Design] AboutUs 페이지 백그라운드 이미지 추가 및 섹션 제거

- src/components/AboutKumapContents/BackgroundContents.jsx
- src/components/AboutKumapContents/ConclusionContents.jsx
- src/pages/AboutKumap.jsx
- 백그라운드 이미지를 수정했습니다.
- z-index를 수정했습니다.
> [Design] 소개 페이지 커밋 누락 사항 수정

- public/index.html
- 메타데이터의 이미지 경로를 절대경로로 변경했습니다.
> [Fix] 메타데이터 이미지 url 경로 수정

- src/components/CourseDetail/CourseDetail.jsx
- 잠깐씩 뜨는 loading 문구 삭제하였습니다
- 예외 로직 다 건드리지는 못할 것 같아서 (나중에 쓰일 수도 있을 것 같아서) 남겨두고 해당 내용만 공백으로 처리했습니다
> [Fix] Loading문구 삭제

- public/index.html
- Open Graph 이미지 사이즈 조절 속성 추가하였습니다
- 진짜 될 겁니다.
> [Fix] Open Graph 이미지 사이즈 조절 속성 추가

- Dockerfile
> [Chore] 소스 복사 코드 순서 변경

- .github/workflows/npm-publish.yml
- Dockerfile
> [Chore] 빌드파일 재수정

- .github/workflows/npm-publish.yml
- Dockerfile
> [Chore] 빌드 스크립트 변경

- src/components/HowToPageContents/HowTo.jsx
- src/components/Tutorial/TutorialModal.jsx
https://github.com/user-attachments/assets/e0628482-1b75-46a0-9009-e82f74decfde
https://github.com/user-attachments/assets/da6c4a53-7868-44c8-bb9c-46ff49b3a3ab
- 튜토리얼 사진
- 그림자 추가 
- 넓이 조정
- 모서리 둥글게
- 소개 페이지 그림자 정도 조정
> [Design] 그림자 등 디자인 조정

- public/index.html
- src/components/FieldSearchBar/SearchBar.jsx
- src/data/RoleData.js
- GA 태그를 추가하여 사이트 통계를 트래킹하도록 했습니다.
- 메타 데이터를 수정하였습니다.
- 검색창 토글 아이콘 클릭시 suggestion 컨텐츠가 보여지는 버블링 현상을 해결하였습니다.
- #192 
- #193 
> [Feat] GA 태그 추가 및 기타 버그 수정

- .github/workflows/npm-publish.yml
- Dockerfile
> [Chore] 빌드 로직 수정

- .github/workflows/npm-publish.yml
- Dockerfile
- public/index.html
- 도커를 이용한 빌드 로직을 제거하였습니다.
- GA 태그를 gtag에서 GTM으로 변경하였습니다.
> [Chore] 도커 빌드 로직 제거 및 GA 태그 매니저 수정

- .eslintrc
- package.json
- src/App.jsx
- src/components/FieldSearchBar/DepartmentList/DepartmentListContents.jsx
- src/components/FieldSearchBar/FieldInput.jsx
- src/components/FieldSearchBar/SearchBar/SearchBar.jsx
- src/components/RoadMap/RoadMap/RoadMapContainer.jsx
- src/hooks/useGA.jsx
- yarn.lock
- [react-ga4](https://www.npmjs.com/package/react-ga4)를 이용하여 GA가 데이터를 수집할 수 있도록 했습니다.
- useGA 커스텀 훅을 만들어 GA api 요청을 보내도록 했습니다.
- 매개변수를 추가하여 데이터를 추적할 수 있도록 했습니다.
```js
const useGA = () => {
const sendClickShareUrl = () => {
const params = { category: 'Button', label: '링크로 공유' };
ReactGA.event('share_url', params);
};
return { sendClickShareUrl };	
};
```
- 의도한 대로 이벤트에 대한 매개변수가 잘 잡히는 것을 알 수 있습니다.
https://stackoverflow.com/questions/75972474/how-to-create-a-custom-event-with-custom-parameters-in-ga4-google-analytics-4
https://www.delasign.com/blog/custom-ga-event-reactjs-gatsbyjs/
> [Feat] react-ga4를 이용한 GA4 적용

- src/components/FieldSearchBar/DepartmentList/DepartmentListContents.jsx
- src/components/FieldSearchBar/FieldInput.jsx
- src/components/FieldSearchBar/FieldSearchBar.jsx
- src/components/FieldSearchBar/SearchBar/SearchBar.jsx
- src/components/FieldSearchBar/SearchLog/index.js
- src/components/FieldSearchBar/SearchLogContent/SearchLogContent.jsx
- src/components/FieldSearchBar/SearchLogContent/index.js
- src/components/FieldSearchBar/index.js
- src/components/RoadMap/Course/CourseCell.jsx
- 직군 검색 시 선택한 소분류에 대한 중,소,세 모두 보여주도록 변경했습니다.
```js
const DropdownItem = styled.div.attrs(({ $isAdd, $courseName }) => ({
id: $isAdd ? `add_${$courseName}` : `remove_${$courseName}`
}))
```
- 내 로드맵 추가 및 삭제에 대한 GA 요청 id 코드도 추가했습니다.
> [FIX] GA 태그를 위한 
